sudo: required
services:
  - docker

before_install:
  - docker build -t laflash/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true laflash/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCES_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: 'us-east-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-371604018441'
  bucket_path: 'docker-react'
  on:
    branch: master
